name: Deploy to VPS

on:
  workflow_run:
    workflows: ["Build and Push Docker Image"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to VPS
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_PRIVATE_KEY }}
          source: "docker-compose.yml"
          target: "/home/${{ secrets.VPS_USERNAME }}/simple-app-ci-cd/"

      - name: Run deployment script on VPS
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_PRIVATE_KEY }}
          script: |
            cd /home/${{ secrets.VPS_USERNAME }}/simple-app-ci-cd/
            docker pull ${{ secrets.DOCKER_USERNAME }}/simple-app-ci-cd:01 
            docker-compose down
            docker-compose up -d
            # docker stop ct-simple-app
            # docker rm ct-simple-app
            # docker run -d --name ct-simple-app -p 9080:80 {{secrets.DOCKER_USERNAME}}/simple-app-ci-cd:01