
name: Build and push

on:
 push:
   branches:
     - main

jobs:
 build-image:
   runs-on: ubuntu-latest
    
   steps:
     - name: Set up Docker Buildx
       uses: docker/setup-buildx-action@v3

     - name: Login to Docker Hub
       uses: docker/login-action@v3
       with:
         username: ${{ secrets.DOCKERHUB_USERNAME }}
         password: ${{ secrets.DOCKERHUB_TOKEN }}
        
     - name: Docker Metadata for Image
       id: docker_meta
       uses: docker/metadata-action@v5
       with:
         images: wahyu1002/shoping-web
         flavor: 
           latest=false
         tags: 
           type=raw,value=0.1.0

     - name: Build and Push to Docker Hub
       id: docker_build
       uses: docker/build-push-action@v5
       with:
         push: true
         tags: ${{ steps.docker_meta.outputs.tags }}
         labels: ${{ steps.docker_meta.outputs.labels }}
         cache-from: type=gha
         cache-to: type=gha,mode=max
         platforms: linux/amd64

     - name: Deploy to AWS EC2 via SSH
       uses: appleboy/ssh-action@master
       with:
          host: ${{ secrets.AWS_HOST }}
          username: ubuntu
          key: ${{ secrets.AWS_KEY }}
          script: |
                docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
                docker pull wahyu1002/shoping-web:0.1.0
                docker stop shoping-web || true
                docker rm shoping-web || true
                docker run -d -p 8080:80 --name shoping-web wahyu1002/shoping-web:0.1.0

         
         
      
      
    